<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cv.igrp.framework</groupId>
        <artifactId>igrp-process-management-backend</artifactId>
        <version>0.1.0-beta.24.8</version>
    </parent>

    <artifactId>process-runtime-activiti</artifactId>
    <name>IGRP Process Manager - Runtime Activiti</name>
    <description>Activiti implementation for the process runtime engine</description>

    <properties>
        <activiti.version>8.6.0</activiti.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>cv.igrp.framework</groupId>
            <artifactId>process-runtime-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.activiti</groupId>
            <artifactId>activiti-spring-boot-starter</artifactId>
            <version>${activiti.version}</version>
        </dependency>

        <dependency>
            <groupId>org.activiti</groupId>
            <artifactId>activiti-spring-security-policies</artifactId>
            <version>${activiti.version}</version>
        </dependency>


    </dependencies>

</project>